### ISSUE TITLE
Clarify rationale around using preloadedDependencies versus bundling dependencies

### ISSUE THREAD

**Issue by kevinrobinson** [h5p/h5p-react#1]
@icc  Hello!  I just ran into H5P, really interesting stuff :)

I'm curious how you think about using `preloadedDependencies`, and why this mechanism exists versus having authors use a build process (eg., browserify, React) to bundle their dependencies.  I was also curious how the JSX example in the readme actually ends up getting transpiled.

Thanks!

**Comment by icc** [comment]
Hi @kevinrobinson ! It's nice to see more people taking an interest in H5P.

The main idea behind H5P is to make it easy to create interactive content for your website and that it should be reusable. The main reason for having dependencies is that we want the website owner to have the power to combine and tailor their own content types from the components that H5P provide. For example, you can choose to only have images and text inside your presentation tool and no tasks of any kind. If the website admin had to rebuild the presentation tool it would just get too complex for most admins to handle and probably more prone to errors as well.
Don't misunderstand, the dependencies between the content types(h5p libraries) is not a replacement for precompilers. You should still be able to use them inside your content type.

For a more concrete example you can have a look at the Glossary Test tool which I'm working on: 
(but keep in mind that in its current state it's more of a prototype)
https://github.com/h5p/h5p-glossary-test

It uses babel with the _react_ and _es2015_ presets. It has dependencies to the H5P React library and [H5P Glossary List](https://github.com/h5p/h5p-glossary-list) which will be re-used by other H5P Content Types.

For performance, the H5P plugin will aggregate the styles and scripts that are needed when the Content is created or saved.

I hope this was a little more clarifying and not just confusing :-)

**Comment by kevinrobinson** [comment]
@icc Thanks for the helpful response!

I follow some of what you're saying, so maybe let's start a little more concrete. :)  If I understand, for [Glossary List](https://github.com/h5p/h5p-glossary-list/blob/master/library.json#L16) the main reason for using `H5P.React` in  `preloadedDependencies`, and listing files individually in `preloadedJs` is to be able to reduce duplication across different H5P components, for performance?

Initially I was expecting H5P components to take one JS entry point (and if components need to use multiple files or external dependencies, they can use whatever build step they choose), so I'm trying to understand how this compares.  Thank you, and much respect for sharing your work here on github :)

**Comment by icc** [comment]
That is correct. All the components with `"runnable": 1` in _library.json_ can be an entry point, i.e. a content type. And as these can be bundled and used by other content types on the fly(in the CMS) it's best to keep large common dependencies, like React, in a separate "library".
In one way we're doing some of the same stuff like e.g. RequireJS, however, the dependencies are separated from the code in order to make it easier for the system/CMS to handle the dependencies.

I may use some of this to try and create a guide on [h5p.org/doc](https://h5p.org/documentation) that better explains how this works.

**Comment by kevinrobinson** [comment]
@icc Thanks for sharing how you're thinking about this!
